#!/bin/sh

# This file is `source`'d before calling `buildkite-agent pipeline upload`, and can be used
# to set up some variables that will be interpolated in the `.yml` pipeline before uploading it.

export CI_TOOLKIT="automattic/a8c-ci-toolkit#31ecbdccf0b22eeddb95a7670fb0c9a0aa88f7d7"
export TEST_COLLECTOR="test-collector#v1.10.1"
