#!/bin/sh

# This file is `source`'d before calling `buildkite-agent pipeline upload`, and can be used
# to set up some variables that will be interpolated in the `.yml` pipeline before uploading it.

export CI_TOOLKIT="automattic/a8c-ci-toolkit#69d45ffb216b9f7f3c24747fd2889ec84218f27b"
export TEST_COLLECTOR="test-collector#v1.10.1"
